<?php
/**
 * @file
 * Code for the SiteNow Articles feature.
 */

include_once 'sitenow_articles.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sitenow_articles_form_ctools_entity_field_content_type_formatter_styles_alter(&$form, &$form_state, $form_id) {
  // We want to act only on the Featured Image (field_image) field.
  if ($form['ctools_field_list']['#value'][0]['field_name'] == 'field_image') {
    // Restrict the view mode options to the entity view modes correspinding to
    // the manual crop options available for this field.
    $form['file_view_mode']['#options'] = array(
      'articles_grid' => t('Article (500x333)'),
      'articles_teaser' => t('Article (650x433)'),
    );
  }
}
